runtime: ruby
env: flex
entrypoint: bundle exec ruby lib/app.rb

# https://cloud.google.com/appengine/docs/flexible/ruby/configuring-your-app-with-app-yaml
  
skip_files:
- spec/
- results/
- docker/
- scripts/
- Rakefile
- README.md
- ^(.*/)?\.sh$
- ^(.*/)?\.jar$
- ^(.*/)?\.example$
- ^(.*/)?\.txt$
- ^(.*/)?\.example$
  